config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'accounts#home'

  
  resources :accounts do
    patch 'update_password', on: :member
    patch 'update_categories', on: :member
    resources :posts, shallow: true do
      resources :comments, only: [:index, :new, :create]
    end
  end
  resources :comments, only: [:edit, :update, :destroy]

  get 'posts', to: 'posts#index'
  get    'register', to: 'accounts#new'
  get    'login', to: 'sessions#new'
  post   'login', to:  'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'contact', to: 'company#index'
  get    'about', to: 'company#show'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :post
	belongs_to :account

	validates :account_id, presence: true
	validates :post_id, presence: true
	validates :body, presence: true, length: {maximum: 2500}

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :correct_account,   only: :destroy

  def index
  end

  # renders new.html.erb view ( make new comment page )
	def new
		@account = Account.find(current_account)
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new
		@comments = @post.comments.all
	end

	# Action to insert new comment into database
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(comment_params)
		@comment.account_id = current_account.id
		if @comment.save
				redirect_to @post
			else
				# dont redirect if the form valication from the model fails
				# instead return to the comments page and show any errors
				render 'new'
			end
	end

	# renders show.html.erb ( show the new comment )
	def show
		@comment = Comment.find(params[:id])
	end

	# renders edit.html.erb ( edit a comment )
	def edit
		@comment = Comment.find(params[:id])
		@account = Account.find(current_account)
		@post = Post.find(@comment.post.id)
		@comments = @post.comments.all
	end

	# Action to update a comment
	def update
		@comment = Comment.find(params[:id])
		@post = Post.find(@comment.post.id)

		if @comment.update(comment_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	# Action to delete comment
	def destroy
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	private
		def comment_params
			params.require(:comment).permit(:body, :account_id, :post_id)
		end

		def correct_account
      @comment = current_account.comments.find_by(id: params[:id])
      redirect_to root_url if @comment.nil?
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-container <%= condenseCategoryName(comment.post.category.name) %>-category">
	<div class="comment-top">
		<% if current_account?(comment.account)%>
			<%= link_to edit_comment_path(comment) do %>
				<span class="comment-author">
	        <i class="glyphicon glyphicon-cog"></i>
	        <span>Edit</span>
	        <div class="comment-triangle"></div>
    		</span>
      <% end %>
		<% else %>
			<%= link_to account_path(comment.account) do %>
				<span class="comment-author">
	        <i class="glyphicon glyphicon-user"></i>
	        <span><%="#{comment.account.first_name} #{comment.account.last_name}"%></span>
	        <div class="comment-triangle"></div>
    		</span>
      <% end %>
		<% end %>

    <div class="comment-delete">
				<% if current_account?(comment.account) %>
					<%= link_to comment_path(comment, :post_id => comment.post.id), method: :delete, data: { confirm: "Are you sure?" } do %>
						<span class="comment-delete-span btn btn-default">
			        <i class="glyphicon glyphicon-trash"></i>
			        <span>Delete</span>
			  		</span>
			  	<% end %>
			  <% end %>
			</div>
	</div>
	
	<div class='comment-bottom'>
		<p class="comment-body"><%= comment.body %></p>

		<div class="comment-commented-on-date">
			Posted 
	  		<abbr title="<%= "#{(comment.created_at).in_time_zone('Eastern Time (US & Canada)').strftime("%m/%d/%Y at %I:%M %p")}" %>">
	  			<%= "#{time_ago_in_words(comment.created_at)} ago" %>
	  		</abbr>
		</div>
	</div>
</div>

app/views/comments/edit.html.erb
<%= content_for(:title, "Edit Comment") %>
<div class="row">
	<div class="form-group col-md-6 col-md-offset-1 side-bar-right">
		<%= render :partial =>"posts/post", locals: {post: @post} %>
		<% if !@comments.nil? %>
			<%= render @comments %>
		<% end %>
	</div>

	<div class="form-group col-md-3 col-md-offset-1">
	<h3>Edit your comment...</h3>
	<%= form_for [@comment], html: {id: "edit_comment_form"} do |f| %>
	<% if @comment.errors.any? %>
				    <div id="error_explanation">
				      <h4>
				        <%= pluralize(@comment.errors.count, "error") %> prohibited
				        this comment from being saved:
				      </h4>
				      <ul>
				        <% @comment.errors.full_messages.each do |msg| %>
				          <li><%= msg %></li>
				        <% end %>
				      </ul>
				    </div>
				    <% end %>
	<%= f.text_area :body, required: true, class: 'form-control comment-box' %> 
	<%= f.submit class: "btn btn-primary" %>

		<% end %>
	</div>
</div>

app/views/comments/new.html.erb
<%= content_for(:title, "Leave Comment") %>
<div class="row">
	<div class="form-group col-md-6 col-md-offset-1 side-bar-right">
		<%= render :partial =>"posts/post", locals: {post: @post} %>
		<% if !@comments.nil? %>
			<%= render @comments %>
		<% end %>
	</div>

	<div class="form-group col-md-3 col-md-offset-1">
	<h3>Leave a comment...</h3>
	<%= form_for [@post, @comment], html: {id: "new_comment_form"} do |f| %>
	<% if @comment.errors.any? %>
				    <div id="error_explanation">
				      <h4>
				        <%= pluralize(@comment.errors.count, "error") %> prohibited
				        this comment from being saved:
				      </h4>
				      <ul>
				        <% @comment.errors.full_messages.each do |msg| %>
				          <li><%= msg %></li>
				        <% end %>
				      </ul>
				    </div>
				    <% end %>
	<%= f.text_area :body, required: true, class: 'form-control comment-box' %> 
	<%= f.submit class: "btn btn-primary" %>

		<% end %>
	</div>
</div>