config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'accounts#home'

  
  resources :accounts do
    patch 'update_password', on: :member
    patch 'update_categories', on: :member
    resources :posts, shallow: true do
      resources :comments, only: [:index, :new, :create]
    end
  end
  resources :comments, only: [:edit, :update, :destroy]

  get 'posts', to: 'posts#index'
  get    'register', to: 'accounts#new'
  get    'login', to: 'sessions#new'
  post   'login', to:  'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'contact', to: 'company#index'
  get    'about', to: 'company#show'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :category
	belongs_to :account
	has_many :comments, dependent: :destroy

	validates :title, presence: true, length: {maximum: 75}
	validates :body, presence: true, length: {maximum: 5000}
	validates :location, presence: true, length: {maximum: 255}
	validates :meeting_time, presence: true
	validates :meeting_date, presence: true
	validates :account_id, presence: true
	validates :category_id, presence: true

	scope :filter_by_category, -> (wanted_category_id){where(category_id: wanted_category_id )}
	scope :sort_by_date, -> (wanted_date){order(updated_at: wanted_date )}
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :correct_account,   only: :destroy

  def index
  	if params[:category]
  		# get the category_id
  		@posts = Post.filter_by_category(params[:category]).sort_by_date(:desc).paginate(page: params[:page], :per_page => 15)
  	elsif params[:date]
  		@wanted_date = params[:date]
  		@posts = Post.sort_by_date(@wanted_date.to_sym).paginate(page: params[:page], :per_page => 15)
  	else
  		@posts = Post.sort_by_date(:desc).paginate(page: params[:page], :per_page => 15)
  	end
  	@categories = Category.all
  end

    # renders new.html.erb view ( make new post page )
	def new
		@account = Account.find(params[:account_id])
		@post = @account.posts.new
	end

	# Action to insert new post into database
	def create
		@post = current_account.posts.build(post_params)
		if @post.save
				redirect_to posts_path
			else
				# dont redirect if the form valication from the model fails
				# instead return to the posts page and show any errors
				render 'new'
			end
	end

	# renders show.html.erb ( show the new post )
	def show
		@post = Post.find(params[:id])
		@comments = @post.comments.all
	end

	# renders edit.html.erb ( edit a post )
	def edit
		@post = Post.find(params[:id])
	end

	# Action to update a post
	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	# Action to delete post
	def destroy
		@post.destroy
		flash[:success] = "Post deleted"
		redirect_to posts_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body, :location, :meeting_date, :meeting_time, :category_id)
		end

		def correct_account
      @post = current_account.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_post.html.erb
<div class="post-container <%= condenseCategoryName(post.category.name) %>-category">
	<div class="post-top">
		<% if current_account?(post.account)%>
			<%= link_to edit_post_path(post) do %>
				<span class="post-author">
	        <i class="glyphicon glyphicon-cog"></i>
	        <span>Edit</span>
	        <div class="triangle"></div>
    		</span>
      <% end %>
		<% else %>
			<%= link_to account_path(post.account) do %>
				<span class="post-author">
	        <i class="glyphicon glyphicon-user"></i>
	        <span><%="#{post.account.first_name} #{post.account.last_name}"%></span>
	        <div class="triangle"></div>
    		</span>
      <% end %>
		<% end %>
		
    <%= image_tag "#{condenseCategoryName(post.category.name)}.png", class: "post-symbol" %>
	
		<h4 class="post-title"><%= link_to post.title, post_path(post) %></h4>
		<span class="post-category"><%= post.category.name %></span>
    <div class="post-details">
    	<span class="post-location">Meet at <%= post.location %></span>
	    </br>
	    <span class="post-meeting-date"><%= "#{(post.meeting_date).strftime("%A, %B %d, %Y") }" %></span>
	    <span class="post-meeting-time">@ <%= "#{(post.meeting_time).strftime("%I:%M %p") }" %></span>
    </div>
	</div>
	
	<div class='post-bottom'>
		<p class="post-body"><%= post.body %></p>
		<div class="post-bottom-details row">
			<div class="col-md-3">
				<%= link_to new_post_comment_path(post) do %>
					<span class="btn btn-default">
					<i class="glyphicon glyphicon-bullhorn"></i>
					<span>Leave Comment (<%= post.comments.count %>)</span>
					</span>
				<% end %>
			</div>
			<div class="col-md-6 post-posted-on-date">
				Posted 
				<abbr title="<%= "#{(post.created_at).in_time_zone('Eastern Time (US & Canada)').strftime("%m/%d/%Y at %I:%M %p")}" %>">
				<%= "#{time_ago_in_words(post.created_at)} ago" %>
				</abbr>
			</div>
			<div class="col-md-3 post-delete">
				<% if current_account?(post.account) %>
					<%= link_to post, method: :delete, data: { confirm: "Are you sure?"} do %>
						<span class="btn btn-default">
						<i class="glyphicon glyphicon-trash"></i>
						<span>Delete</span>
						</span>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<%= content_for(:title, "Edit Post") %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="post_form">
			<span class="form_header">Edit Post</span>
				<%= form_for [@account, @post], html: {id: "edit_post_form", autocomplete: 'off'} do |f| %>
					<% if @post.errors.any? %>
				    <div id="error_explanation">
				      <h4>
				        <%= pluralize(@post.errors.count, "error") %> prohibited
				        this account from being saved:
				      </h4>
				      <ul>
				        <% @post.errors.full_messages.each do |msg| %>
				          <li><%= msg %></li>
				        <% end %>
				      </ul>
				    </div>
				    <% end %>
			<%= f.label :title, "Title: " %>
			<%= f.text_field :title, required: true, class: 'form-control' %> 
			<%= f.label :locaiton, "Location: " %>
			<%= f.text_field :location, required: true, class: 'form-control' %> 
			<%= f.label :meeting_date, "Meeting Date: " %>
					<%= f.text_field :meeting_date, required: true, :'data-provide' => 'datepicker', :'data-date-format' => 'yyyy-mm-dd', class: 'form-control' %> 
			<%= f.label :meeting_time, "Meeting Time: " %>
			<%= f.text_field :meeting_time, required: true, class: 'form-control datetimepicker' %>
			<%= f.label :category_id, "Category: " %>
			<%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a Category"}, {class: "form-control"} %> 
			<%= f.label :body, "Body: " %>
			<%= f.text_area :body, required: true, class: 'form-control' %> 

			<%= f.submit class: "btn btn-default btn btn-primary" %>


		<% end %>

			</div>
	</div>
	<script type="text/javascript">
      $(function () {
          $('#post_meeting_time').datetimepicker({
              format: 'LT'
          });
      });
  </script>
</div>

app/views/posts/index.html.erb
<%= content_for(:title, "View All Posts") %>
<h1>View Posts Feed</h1>
<div class="row">
	<div class="form-group col-md-3 col-md-offset-1" id="search_bar">
		<h3>Filter Posts</h3>

		<div id="search_box">
			<h4>By: Date</h4>
			<div class="date-filter-buttons">
				<%= link_to posts_path({:date => "desc"}) do %>
					<div class="btn btn-default">
						<i class="glyphicon glyphicon-arrow-down"></i>
						<span>Newest</span>
					</div>
				<% end %>	

				<%= link_to posts_path({:date => "asc"}) do %>
					<div class="btn btn-default">
						<i class="glyphicon glyphicon-arrow-up"></i>
						<span>Oldest</span>
					</div>
				<% end %>	
			</div>
			<h4>By Category:</h4>
			<div class="category-filter-buttons">
				<% @categories.each do |c| %>
					<%= link_to posts_path({:category => c.id}) do %>
						<div class="btn btn-default">
							<%= image_tag "#{condenseCategoryName(c.name)}.png", class: "filter-category-symbol" %>
							<span><%= c.name %></span>
						</div>
					<% end %>	
				<% end %>	
			</div>
		</div>
	</div>

	<div class="form-group col-md-6 col-md-offset-1">
		<%= render @posts %>
		<%= will_paginate @posts %>
	</div>
</div>

app/views/posts/new.html.erb
<%= content_for(:title, "Make a New Post") %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="post_form">
			<span class="form_header">Make a Post</span>
				<%= form_for [@account, @post], html: {id: "new_post_form", autocomplete: 'off'} do |f| %>
					<% if @post.errors.any? %>
				    <div id="error_explanation">
				      <h4>
				        <%= pluralize(@post.errors.count, "error") %> prohibited
				        this account from being saved:
				      </h4>
				      <ul>
				        <% @post.errors.full_messages.each do |msg| %>
				          <li><%= msg %></li>
				        <% end %>
				      </ul>
				    </div>
				    <% end %>
					<%= f.label :title, "Title: " %>
					<%= f.text_field :title, required: true, class: 'form-control' %> 
					<%= f.label :locaiton, "Location: " %>
					<%= f.text_field :location, required: true, class: 'form-control' %> 
					<%= f.label :meeting_date, "Meeting Date: " %>
					<%= f.text_field :meeting_date, required: true, :'data-provide' => 'datepicker', :'data-date-format' => 'yyyy-mm-dd', class: 'form-control' %> 
					<%= f.label :meeting_time, "Meeting Time: " %>		   
					<%= f.text_field :meeting_time, required: true, class: 'form-control datetimepicker' %>
					<%= f.label :category_id, "Category: " %>
					<%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a Category"}, {class: "form-control"} %> 
						<%= f.label :body, "Body: " %>
					<%= f.text_area :body, required: true, class: 'form-control' %> 

					<%= f.submit class: "btn btn-default btn btn-primary" %>
				<% end %>
		</div>
	</div>
    <script type="text/javascript">
      $(function () {
          $('#post_meeting_time').datetimepicker({
              format: 'LT'
          });
      });
  </script>
</div>

app/views/posts/show.html.erb
<%= content_for(:title, "View Post") %>
<h1>View Post</h1>
<div class="row">
	<div class="form-group col-md-6 col-md-offset-3">
		<%= render @post %>
		<%= render @comments %>
	</div>
</div>