config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'accounts#home'

  
  resources :accounts do
    patch 'update_password', on: :member
    patch 'update_categories', on: :member
    resources :posts, shallow: true do
      resources :comments, only: [:index, :new, :create]
    end
  end
  resources :comments, only: [:edit, :update, :destroy]

  get 'posts', to: 'posts#index'
  get    'register', to: 'accounts#new'
  get    'login', to: 'sessions#new'
  post   'login', to:  'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'contact', to: 'company#index'
  get    'about', to: 'company#show'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :require_login

  private
		# Confirms a logged-in user.
	  def require_login
	    unless logged_in?
	    	store_location
	      flash[:danger] = "Please log in to access this part of the site."
	      redirect_to login_path
	    end
	  end

	  def root_url_visit
	  	unless logged_in?
	      redirect_to login_path
	  	end
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title='')
		base_title = "LeapUp"

		if(page_title.empty?)
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end

	def condenseCategoryName(name)
		name.gsub(/\s+/, "").downcase
	end
end

app/views/application/_footer.html.erb
<footer class=".footer">
	<small>&#169; Leapup created by 
		<%= link_to "SDLC Corp", "https://github.com/ashleypackard/LeapUp" %>
	</small>
	<nav>
		<ul>
			<li><%= link_to "News", "http://news.railstutorial.org/" %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/application/_header_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
  	<span class="navbar-brand" id="brand">LeapUp</span>
  	<ul class="nav navbar-nav">
      <li class="<%= 'active' if params[:controller] == 'accounts' && params[:action] == 'home' %>">
        <%= link_to root_url do %>
          <i class="glyphicon glyphicon-home"></i>
          <span>Home</span>
        <% end %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'posts' && params[:action] == 'index'  %>">
        <%= link_to posts_path do %>
          <i class="glyphicon glyphicon-eye-open"></i>
          <span>View Feed</span>
         <% end %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'posts' && params[:action] == 'new' %>">
        <%= link_to new_account_post_path(current_account) do %>
          <i class="glyphicon glyphicon-pencil"></i>
          <span>Make Post</span>
         <% end %>
      </li>      
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown <%= 'active' if params[:id] && params[:controller] == 'accounts' && current_account?(Account.find(params[:id])) && (params[:action] == 'show' || params[:action] == 'edit')%>">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= "#{current_account.first_name} #{current_account.last_name}" %> <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li class="<%= 'active' if params[:id] && params[:controller] == 'accounts' && current_account?(Account.find(params[:id])) && params[:action] == 'show' %>">
            <%= link_to account_path(current_account) do %>
              <i class="glyphicon glyphicon-user"></i>
              <span>Profile</span>
            <% end %>
          <li class="<%= 'active' if params[:controller] == 'accounts' && params[:action] == 'edit' %>">      
            <%= link_to edit_account_path(current_account) do %>
              <i class="glyphicon glyphicon-cog"></i>
              <span>Settings</span>
            <% end %>
          </li>
          <li>
            <%= link_to logout_path, method: "delete" do %>
              <i class="glyphicon glyphicon-log-out"></i>
              <span>Logout</span>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/application/_html_head.html.erb
<title><%= title %></title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'layout_app', media: 'all', 'data-turbolinks-track' => true %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>