config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  root 'accounts#home'

  
  resources :accounts do
    patch 'update_password', on: :member
    patch 'update_categories', on: :member
    resources :posts, shallow: true do
      resources :comments, only: [:index, :new, :create]
    end
  end
  resources :comments, only: [:edit, :update, :destroy]

  get 'posts', to: 'posts#index'
  get    'register', to: 'accounts#new'
  get    'login', to: 'sessions#new'
  post   'login', to:  'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'contact', to: 'company#index'
  get    'about', to: 'company#show'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/account.rb
class Account < ActiveRecord::Base

	attr_accessor :remember_token
  attr_accessor :updating_password # virtual attribute to detect update password form

  has_many :account_categories, dependent: :destroy
	has_many :categories, through: :account_categories
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy

	has_secure_password

	before_save { self.email = email.downcase }
	validates :first_name, presence: true, length: {maximum: 100}
	validates :last_name, presence: true, length: {maximum: 100}
	
	VALID_EMAIL_REGEX = /\A[a-zA-Z]+[\d]*@wit\.edu+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            				format: { with: VALID_EMAIL_REGEX },
           					uniqueness: { case_sensitive: false}

  validates :password, presence: true, length: {minimum: 6}, on: :create
  validates :password, presence: true, length: {minimum: 6}, if: :updating_password?
  # validates :password, presence: true, length: {minimum: 6}, on: :update, allow_blank: true
  #validates :password, presence: true, length: {minimum: 6}, on: :create
	#validates :password, presence: true, length: {minimum: 6}, allow_blank: true
	#validates :password, length: {minimum: 6}, on: :update, allow_blank: :true

	VALID_PHONE_REGEX = /\A[\d]{10}\z/i
	validates :phone_number, length: {maximum: 10},
													 format: {with: VALID_PHONE_REGEX},
													 allow_blank: true

  def updating_password?
    updating_password
  end
  # Returns the hash digest of the given string.
  def Account.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

 # Returns a random token.
  def Account.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers an account in the database for use in persistent sessions.
  def remember
    self.remember_token = Account.new_token
    update_attribute(:remember_digest, Account.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a account.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	layout 'login', only: [:new]
	skip_before_action :require_login, only: [:new, :create, :home]
	before_action :root_url_visit, only: [:home]
	before_action :validate_correct_account, only: [:edit, :update, :destroy]

  def index
  end

  def home
  	@recent_posts = current_account.posts.sort_by_date(:desc).take(5)
  	@related_posts = []
  	current_account.categories.each do |category|
  		category.posts.sort_by_date(:desc).take(3).each { |post| @related_posts.push(post) if post.account != current_account }
  	end
  	@related_posts.shuffle!
  end

  # renders new.html.erb view ( register page )
	def new
		redirect_to current_user if logged_in?
		@account = Account.new
	end

	# Action to insert new user into database
	def create
		@account = Account.new(account_params)
		if @account.save
				log_in @account
				redirect_to @account
			else
				# dont redirect if the form validation from the model fails
				# instead return to the articles page and show any errors
				render 'new', layout: "login"
			end
	end

	# renders show.html.erb ( a users profile page )
	def show
		@account = Account.find(params[:id])
		@posts_list = @account.posts.sort_by_date(:desc).paginate(page: params[:page], :per_page => 10)
		@category_list = @account.categories
	end

	# renders edit.html.erb ( account settings page )
	def edit
		@account = Account.find(params[:id])
		@categories = Category.all
	end

	# Action to update account settings
	def update		
		@account = Account.find(params[:id])
		@account.updating_password = false

		if @account.update_attributes(edit_account_params)
			flash[:success] = "Your account settings have been successfully updated."
			redirect_to @account
		else
			render 'edit'
		end
	end

	def update_password
		@account = Account.find(params[:id])
		@account.updating_password = true

		if @account.update_attributes(change_password_params)
			flash[:success] = "Your password has been successfully updated."
			redirect_to @account
		else
			render 'edit'
		end
	end

	def update_categories
		@account = Account.find(params[:id])
		@account.account_categories.delete_all

		if params[:categories]
			params[:categories].each do |category|
				@account.account_categories.create(category_id: category)
			end
		end

		flash[:success] = "Your interests have been successfully updated."
		redirect_to @account
	end

	# Action to delete account
	def destroy
		@account = Account.find(params[:id])
		@account.destroy
		flash[:success] = "You have successfully deleted your account."
		redirect_to login_path
	end

	private

		def account_params
			params.require(:account).permit(:first_name, :last_name, :email, :password, :password_confirmation)
		end

		def change_password_params
			params.require(:account).permit(:password, :password_confirmation)
		end

		def edit_account_params
			params.require(:account).permit(:first_name, :last_name, :description)
		end

		def validate_correct_account
		  @account = Account.find(params[:id])
      redirect_to(root_url) unless current_account?(@account)
	  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<%= content_for(:title, "Settings") %>
<h1>Account Settings</h1>
<% if @account.errors.any? %>
	<div id="error_explanation">
		<h4>
			<%= pluralize(@account.errors.count, "error") %> prohibited
			this account from being saved:
		</h4>
		<ul>
			<% @account.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class="row">
	<div class="form-group col-md-6 right-border">
		<%= form_for @account, html: { id: "sign_up_form", autocomplete: 'off'} do |f| %>
			<%= f.label :first_name, 'First Name: ' %>
			<%= f.text_field :first_name, required: true, placeholder: "Joe", class: "form-control" %>
			<%= f.label :last_name, 'Last Name: ' %>
			<%= f.text_field :last_name, required: true, placeholder: "Smith", class: "form-control" %>
			<%= f.label :email, 'Email: ' %>
			<%= f.text_field :email, readonly: true, class: "form-control" %>
			<%= f.label :description, 'Bio: ' %>
			<%= f.text_area :description, placeholder: "Add something about yourself...", class: "form-control" %>
			<div class="submit_container">
				<%= button_tag(type: 'submit', class: "btn btn-default short_btn") do %>
					 <i class="glyphicon glyphicon-wrench"></i> Update Account
				<% end %>
			</div>
		<% end %>

		<h2>Change Password</h2>
		<%= form_for @account, html: { id: "sign_up_form"}, url: update_password_account_path(@account) do |f| %>
			<%= f.label :password, 'New Password: ' %>
			<%= f.password_field :password, required: true, placeholder: "New Password", class: "form-control" %>
			<%= f.label :password_confirmation, 'Confirm New Password: ' %>
			<%= f.password_field :password_confirmation, required: true, placeholder: "New Password Again", class: "form-control" %>
			<div class="submit_container">
				<%= button_tag(type: 'submit', class: "btn btn-default short_btn") do %>
					 <i class="glyphicon glyphicon-cog"></i> Change Password
				<% end %>	
			</div>
		<% end %>
	</div>

	<div class="col-md-6">
		<h3>Choose your categories</h3>
		<div>
			<%= form_for @account, html: { id: "category_select"}, url: update_categories_account_path(@account) do |f| %>
				<% @categories.each do |c| %>
					<%= label_tag condenseCategoryName(c.name) do %>
						<div class="row">
							<div class="col-md-1"><%= check_box_tag "categories[]", c.id, @account.categories.include?(c), id: condenseCategoryName(c.name) %></div>
							<div class="col-md-1"><%= image_tag "#{condenseCategoryName(c.name)}.png", class: "preferred-category-symbol" %></div>
							<div class="col-md-10"><%= c.name %></div>
						</div>
					<% end %>				
				<% end %>
				<div class="submit_container">
					<%= button_tag(type: 'submit', class: "btn btn-default short_btn") do %>
						 <i class="glyphicon glyphicon-heart"></i> Update Categories
					<% end %>
				</div>
			<% end %>
		</div>
	</div> <!-- end col-md-6 -->
</div> <!-- row -->

<div id="delete_container">
	<h3>Delete your account</h3>
	<p>We're sorry to see you go! Please tell us why you no longer want an account:</p>
	<p> leapup-accounts@gmail.com</p>
	<%= link_to 'Delete Forever', account_path(@account), class: "btn btn-danger short_btn", method: :delete, data: {confirm: "Are you sure?"} %>
</div> <!-- end delete_container -->

app/views/accounts/home.html.erb
<h1><%= "#{current_account.first_name} #{current_account.last_name}" %></h1>

<div class="row">
	<div class="col-md-6 right-border">
		<h3>Your recent posts</h3>
		<% if @recent_posts.any? %>
			<%= render @recent_posts %>
		<% else %>
			<i>You do not have any posts yet! Why don't you make your first <%= link_to "post", new_account_post_path(current_account) %>?</i>
		<% end %>
	</div>

	<div class="col-md-6">
		<h3>Posts that interest you</h3>
		<% if @related_posts.any? %>
			<%= render @related_posts %>
		<% else %>
			<i> No posts to show. Make sure to set up your preferred categories in your <%= link_to "account settings", edit_account_path(current_account) %>.</i>
		<% end %>
	</div>
</div>

app/views/accounts/new.html.erb
<%= content_for(:title, "Sign Up") %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="account_form">
			<span class="form_header">Sign Up</span>
				<%= form_for @account, html: { id: "sign_up_form", autocomplete: 'off'} do |f| %>
					<% if @account.errors.any? %>
				    <div id="error_explanation">
				      <h4>
				        <%= pluralize(@account.errors.count, "error") %> prohibited
				        this account from being saved:
				      </h4>
				      <ul>
				        <% @account.errors.full_messages.each do |msg| %>
				          <li><%= msg %></li>
				        <% end %>
				      </ul>
				    </div>
				  <% end %>
						
					<%= f.label :first_name, 'First Name: ' %>
					<%= f.text_field :first_name, required: true, placeholder: "Joe", class: 'form-control' %>
					<%= f.label :last_name, 'Last Name: ' %>
					<%= f.text_field :last_name, required: true, placeholder: "Smith", class: 'form-control' %>
					<%= f.label :email, 'Email: ' %>
					<%= f.text_field :email, required: true, placeholder: "smithj@wit.edu", class: 'form-control' %>
					<%= f.label :password, 'Password: ' %>
					<%= f.password_field :password, required: true, placeholder: "Password", class: 'form-control' %>
					<%= f.label :password_confirmation, 'Confirm Password: ' %>
					<%= f.password_field :password_confirmation, required: true, placeholder: "Password Again", class: 'form-control' %>
					<%= f.submit class: "btn btn-default btn btn-primary" %>

				<% end %>
		</div>
	</div>
</div>

app/views/accounts/show.html.erb
<%= content_for(:title, "Account Profile") %>
<h1><%= "#{@account.first_name} #{@account.last_name}" %></h1>
<h5><%= "#{@account.email}" %></h5>
<div class="row">
	<div class="col-md-4 col-md-offset-1 right-border">
		<h3><b>Bio</b></h3>
		<p>
		<% if @account.description.blank? %>
			<i>This user has not written a bio yet.</i>
		<% else %>
			<%= @account.description %>
		<% end %>
		</p>

		<h3><b>Favorite Categories</b></h3>
		<div>
			<% if @category_list.empty? %>
				<i>This user has no preferred categories.</i>
			<% else %>
				<% @category_list.each do |category| %>
					<div class="row">
						<div class="col-md-2"> <%= image_tag "#{condenseCategoryName(category.name)}.png", class: "preferred-category-symbol" %> </div>
						<div class="col-md-10"> <%= category.name %> </div>
					</div>
				<% end %>
			<% end %>
		</div>

	</div>

	<div class="col-md-6 col-md-offset-1">
		<% if @posts_list.any? %>
			<%= render @posts_list %>
			<%= will_paginate @posts_list %>
		<% else %>
			<i>You do not have any posts yet! Why don't you make your first <%= link_to "post", new_account_post_path(current_account) %>?</i>
		<% end %>
	</div>
</div>